spring:
  application:
    name: event-service
  config:
    import: optional:configserver:http://config:8888
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20