# STAGE 1
# base image
FROM openjdk:11-slim

# label
LABEL maintainer="Robby Quintiens <robby.quintiens@student.pxl.be>"

# app jar-file
ARG JAR_FILE

# copy app jar to container
COPY ${JAR_FILE} app.jar

# unpackage jar file
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf /app.jar)

# STAGE2
# same Java runtime
FROM openjdk:11-slim

# add volume pointing to /tmp
VOLUME /tmp

# copy unpackaged app to new container
ARG DEPENDENCY=/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

# execute the app
ENTRYPOINT ["java", "-cp", "app:app/lib/*","com.jevent.eventservice.EventServiceApplication"]