spring:
  cloud:
    consul:
      host: discovery
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        health-check-url: http://event-service:8081/actuator/health
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
